- repo: https://github.com/psf/black
  rev: 21.9b0
  hooks:
    - id: black
      language_version: python3

- repo: https://github.com/charliermarsh/ruff
  rev: v0.0.0
  hooks:
    - id: ruff
      language_version: python3

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
    - id: mypy
      language_version: python3

- repo: https://github.com/pre-commit/mirrors-pyyaml
  rev: v5.4
  hooks:
    - id: pyyaml
      language_version: python3

- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v7.32.0
  hooks:
    - id: eslint
      language_version: python3
