# config/users/user_template.yaml

# ── Metadata ───────────────────────────────────────────────────────────
key: john-doe # unique identifier
role: > # high-level category (teacher, casual, etc.)
  friend.

  John is just a everyday normal guy.

description: > # short human-readable summary
  Just a everyday normal guy

context:
  timezone: Europe/Berlin
  threshold_seconds: 3600
  template: >
    {% if delta_seconds >= user.context.threshold_seconds %}
    To tailor your next answer, use
    what you talked about last,
    when you wrote your last message, and the temporal distance to
    what {{user.identity.name}} is writing now at the current time of the day:

    Last reply by {{ char.identity.name }} was
    on {{ day_of_week_last }}, {{ date_last }}
    at {{ hour_last }}:{{ minute_last }}.
    {% endif %}

    {{user.identity.name}} is writing now
    on {{ day_of_week_now }}, {{ date_now }}
    at {{ hour_now }}:{{ minute_now }}.

identity:
  name: "Johnny"
  first: "John"
  last: "Doe"
