# config/users/<user-key>.yaml

# ── Metadata ───────────────────────────────────────────────────────────
key: john-doe # unique identifier
role: Friend # high-level category (teacher, casual, spicy, etc.)
description: > # short human-readable summary
  Just a everyday normal guy

identity:
  name: "Johnny"
  first: "John"
  last: "Do"
  age: 29
  biography:
    - "Born in London"
    - "Studied economics"
  appearance:
    - "Chubby"
  personality:
    - "curious"
    - "many interests"
  hobbies_skills:
    - "programming in Python"
  interests:
    - "Cats"
    - "Movies"
