# config/commands.yaml

help:
  usage: "/help"
  description: "Show this message"

model:
  usage: "/model [<model_name>]"
  description: "Show info about the current (or given) model"

showsettings:
  usage: "/showset"
  description: "Show current service, model, temperature & max tokens"

services:
  usage: "/services"
  description: "List available services"

models:
  usage: "/models"
  description: "List models for current service"

cservice:
  usage: "/cservice <service_name>"
  description: "Change service (e.g. mistral or groq)"

cmodel:
  usage: "/cmodel <model_name>"
  description: "Change model of current service"

maxtokens:
  usage: "/maxtokens <int>"
  description: "Change max tokens (positive integer)"

temperature:
  usage: "/temp <float>"
  description: "Change model's temperature (0.0–2.0)"

setasdefaults:
  usage: "/setdefault"
  description: "Persist current settings as defaults"

factoryreset:
  usage: "/factoryreset"
  description: "Reset to factory defaults"
