# config/commands.yaml
# To Do: line breaks in CLI

help:
  usage: "/help"
  description: "Show this message"

showsettings:
  usage: "/showset"
  description: "Show current service, model, temperature & max tokens"

services:
  usage: "/services"
  description: "List available services: [draw services from yamle]"

bots:
	usage: "/bots"
    description: "List available bots: [draw them from yaml file]"

cservice:
  usage: "/cservice <service_name>"
  description: "Change service (e.g. mistral or groq)" # and show settings

model:
  usage: "/model [<model_name>]"
  description: "Show info about the current (or given) model"

models:
  usage: "/models"
  description: "List models for current service"

cmodel:
  usage: "/cmodel <model_name>"
  description: "Change model of current service"

maxtokens:
  usage: "/maxtokens <int>"
  description: "Change max tokens (positive integer)"

temperature:
  usage: "/temp <float>"
  description: "Change model's temperature (0.0–2.0)"

setasdefaults:
  usage: "/setdefaults"
  description: "Persist current settings as defaults"

factoryreset:
  usage: "/factoryreset"
  description: "Reset to factory defaults"

## Todo: From here on to be implemented
defaults:
  usage: "/resdefault"
  description: "restore your defaults (and show list model + settings)"

restoredefaults:
  usage: "/resdefault"
  description: "restore your defaults (and show list model + settings)"

# Save responses or inputs
saveresponse:
  usage: "/s [<filename>]"
  description: "save last reponse"

saveresponsenamed:
  usage: "/sn"
  description: "save last response & ask for filename" # do not update history with that

saveeuser:
  usage: "/su [<filename>]"
  description: "save previous user input"

# Summarize
summarize:
  usage: "/summarize"
  description: "summarize history and ask if supposed to use as history or provided as message to adjust"
sumthis:
  usage: "/sumthis [<text>]"
  description: "use this text as summary"

# History
histtoggle:
  usage: "f/sf [filename]"
  description: save attached file (without sending it to LLM)"

histsave:
  usage: "f/sf [filename]"
  description: save attached file (without sending it to LLM)"

histload:
  usage: "f/sf [filename]"
  description: save attached file (without sending it to LLM)"

histories:
  usage: "/sn"
  description: "show stored histories"

histshow:
  usage: "f/hshow [filename]"
  description: list plus 1 (in reverse -1, -2,)"

histdelete:
  usage: "f/hdel [<entry>]"
  description: save attached file (without sending it to LLM); ask for confirmation"

# Jailbreaks
jailbreaks:
  usage: "f/jbshow"
  description: "show list of jailbreaks"

sendjailbreak:
  usage: "f/jbs <int>"
  description: "show list of jailbreaks"

# Telegram exclusive
savestring:
  usage: "/savethis [<filename>]"
  description: save a string to file (without sending it to LLM)"

savefile:
  usage: "f/sf [filename]"
  description: save attached file (without sending it to LLM)"
